CREATE USER <DYNATRACE_USER> IDENTIFIED BY <PASSWORD>;
GRANT CREATE SESSION TO <DYNATRACE_USER> CONTAINER=ALL;

GRANT SELECT ON GV_$ARCHIVE_DEST TO <DYNATRACE_USER> CONTAINER = ALL; 
GRANT SELECT ON GV_$ARCHIVE_DEST_STATUS TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON V_$ASM_DISK_STAT TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON V_$ASM_DISKGROUP_STAT TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON V_$BACKUP_SET_DETAILS to <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$CLUSTER_INTERCONNECTS TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$CONTAINERS TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON V_$CONTAINERS TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$CON_SYSSTAT TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$CON_SYS_TIME_MODEL TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$DATABASE TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON V_$DATABASE TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON V_$DATABASE_BLOCK_CORRUPTION TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$DATAFILE TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON V_$DATAFILE TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$DATAGUARD_STATUS TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$INSTANCE TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$INSTANCE_PING TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$LIBRARYCACHE TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON V_$LOG TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$METRIC TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$METRICGROUP TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$PARAMETER TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$PDBS TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$PGASTAT TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON V_$RECOVER_FILE TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON V_$RECOVERY_FILE_DEST TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$RESOURCE_LIMIT TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON V_$RMAN_BACKUP_JOB_DETAILS TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$SESSION TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON V_$SESSION TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$SGASTAT TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$SQL TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON V_$SQL TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$SQLAREA TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$SQL_PLAN TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$SQL_PLAN_STATISTICS_ALL TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$SYSSTAT TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$SYSTEM_EVENT TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON GV_$SYSTEM_WAIT_CLASS TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON V_$TABLESPACE TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON V_$TEMPFILE TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON CDB_TEMP_FILES TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON CDB_DATA_FILES TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON CDB_TABLESPACES TO <DYNATRACE_USER> CONTAINER = ALL;
GRANT SELECT ON CDB_TABLESPACE_USAGE_METRICS TO <DYNATRACE_USER> CONTAINER = ALL;
 
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.GV_$CONTAINERS CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.V_$CONTAINERS CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.GV_$CON_SYSSTAT CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.GV_$CON_SYS_TIME_MODEL CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.V_$DATABASE_BLOCK_CORRUPTION CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.GV_$DATAFILE CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.V_$DATAFILE CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.GV_$PDBS CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.GV_$SESSION CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.V_$TABLESPACE CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.V_$TEMPFILE CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.V_$RECOVER_FILE CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.GV_$SQL CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.V_$SQL CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.GV_$SQLAREA CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.CDB_TEMP_FILES  CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.CDB_DATA_FILES CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.CDB_TABLESPACES CONTAINER = CURRENT;
ALTER USER <DYNATRACE_USER> SET CONTAINER_DATA=ALL FOR SYS.CDB_TABLESPACE_USAGE_METRICS CONTAINER = CURRENT;


-- RAC only. This section will create an ACL and grant the Dynatrace user
-- permissions to query the local IP of each instance. This is used to establish
-- the relationship between OneAgent detected hosts and the database instances.
-- Feel free to comment this section out if you are not running a multi-instance setup.

BEGIN
  DBMS_NETWORK_ACL_ADMIN.create_acl (
    acl          => 'dynatrace.xml', 
    description  => 'Allow DNS resolution checks to get RAC node IP addresses',
    principal    => '<DYNATRACE_USER>',
    is_grant     => TRUE, 
    privilege    => 'resolve',
    start_date   => SYSTIMESTAMP,
    end_date     => NULL);
    
        FOR instance_host IN (
        SELECT DISTINCT host_name
    FROM gv$instance -- Retrieves all RAC node hostnames
  ) LOOP
    DBMS_NETWORK_ACL_ADMIN.assign_acl (
      acl         => 'dynatrace.xml',
      host        => instance_host.host_name, -- Assign ACL to each instance host
      lower_port  => NULL,
      upper_port  => NULL
    );
  END LOOP;

  COMMIT;
END;
/
